export const GET_QUEUE_LIST = 'GET_QUEUE_LIST';

// Settings
export const SET_CATEGORY_SETTINGS_LIST = 'SET_CATEGORY_SETTINGS_LIST';
export const SET_CATEGORY_CONTENT = 'SET_CATEGORY_CONTENT';

// Home
export const SET_PERSONAL_DETAILS_LIST = 'SET_PERSONAL_DETAILS_LIST';
