export const GET_QUEUE_LIST = 'GET_QUEUE_LIST';
export const GET_PATIENT_DETAILS = 'GET_PATIENT_DETAILS';

// Settings
export const SET_CATEGORY_SETTINGS_LIST = 'SET_CATEGORY_SETTINGS_LIST';
export const SET_CATEGORY_CONTENT = 'SET_CATEGORY_CONTENT';
